version: "3.5"

volumes:
  postgres_data:
  static_data:
  media_data:
  nginx_config:

services:
  db:
    image: postgres:13.2
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: izdez/foodgram:latest
    container_name: web
    restart: always
    volumes:
      - static_data:/code/static/
      - nginx_config:/code/nginx/
      - media_data:/code/media
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    volumes:
      - static_data:/code/static/
      - media_data:/code/media/
      - nginx_config:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - web